# Generated by Django 5.1.7 on 2025-03-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nom_complet',
            new_name='prenoms',
        ),
    ]
