# Generated by Django 5.1.6 on 2025-04-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conges',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
